version: '3.9'

services:
  sm_assignment:
    image: php_assignment:latest
    container_name: php_assignment
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
      target: local
    ports:
      - "7777:80"
    volumes:
      - "./tests/:/app/tests/"
      - "./composer.json:/app/composer.json"
      - "./composer.lock:/app/composer.lock"
      - "./phpunit.xml:/app/phpunit.xml"
      - "./doc/:/app/doc/"
      - "./doc/docker/php.ini:/usr/local/etc/php/php.ini"

networks:
  default:
    name: sm_assignment
